run:
  timeout: 5m
  go: '1.19'

linters:
  enable-all: true
  disable:
    - nosnakecase # Replaced by 'unused'
    - varcheck # Replaced by 'unused'
    - deadcode # Replaced by 'unused
    - golint # Replaced by 'revive'
    - exhaustivestruct # Replaced by 'exhaustruct'
    - interfacer # The repository of the linter has been archived by the owner
    - scopelint # Replaced by 'exportloopref'
    - ifshort # The repository of the linter has been deprecated by the owner
    - maligned # Replaced by govet 'fieldalignment'
    - structcheck # Replaced by 'unused'
    - goimports # see https://github.com/golangci/golangci-lint/issues/1490
    - gofumpt # see https://github.com/golangci/golangci-lint/issues/1490
    - wrapcheck
    - gochecknoglobals
    - ireturn
    - exhaustruct
    - goerr113
    - containedctx
    - gochecknoinits
    - paralleltest
    - cyclop
    - nestif
    - nakedret
    - gosec
    - funlen
    - lll
    - gocognit
    - nonamedreturns
    - gomnd

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - funlen
        - govet
        - cyclop
        - wsl

linters-settings:
  varnamelen:
    ignore-names:
      - err
      - ch
    ignore-decls:
      - c context.Context
      - t testing.T
      - i int
      - j int
      - k int
      - T any
      - ok bool
